package rchat.info.ctrlftp.core.responses;

public enum ResponseTypes {
    COMMAND_OK(200),
    SYNTAX_ERROR(500),
    BAD_PARAMETERS(501),
    NOT_IMPLEMENTED_SUPERFLUOUS(202),
    NOT_IMPLEMENTED(502),
    BAD_SEQUENCE_OF_COMMANDS(503),
    COMMAND_NOT_IMPLEMENTED_FOR_PARAMETER(504),
    RESTART_MARKER(110),
    SYSTEM_STATUS(211),
    DIRECTORY_STATUS(212),
    FILE_STATUS(213),
    HELP_MESSAGE(214),
    SYSTEM_TYPE(215),
    SERVICE_READY_IN_N_MINUTES(120),
    SERVICE_READY_FOR_NEW_USER(220),
    SERVICE_CLOSING_CONTROL_CONNECTION(221),
    SERVICE_NOT_AVAILABLE(421),
    DATA_CONNECTION_ALREADY_OPEN(125),
    DATA_CONNECTION_OPEN(225),
    CANT_OPEN_DATA_CONNECTION(425),
    CLOSING_DATA_CONNECTION(226),
    TRANSFER_ABORTED(426);

    public int code;

    ResponseTypes(int code) {
        this.code = code;
    }
}
