package rchat.info.ctrlftp.core.responses;

public enum ResponseTypes {
    RESTART_MARKER(110),
    SERVICE_READY_IN_N_MINUTES(120),
    DATA_CONNECTION_ALREADY_OPEN(125),
    ABOUT_TO_OPEN_CONNECTION(150),

    COMMAND_OK(200),
    NOT_IMPLEMENTED_SUPERFLUOUS(202),
    SYSTEM_STATUS(211),
    DIRECTORY_STATUS(212),
    FILE_STATUS(213),
    HELP_MESSAGE(214),
    SYSTEM_TYPE(215),
    SERVICE_READY_FOR_NEW_USER(220),
    SERVICE_CLOSING_CONTROL_CONNECTION(221),
    DATA_CONNECTION_OPEN(225),
    CLOSING_DATA_CONNECTION(226),
    ENTERING_PASSIVE_MODE(227),
    AUTH_SUCCESS(230),
    FILE_ACTION_OK(250),
    PATHNAME_CREATED(257),

    USERNAME_OK_NEED_PASS(331),
    NEED_ACCOUNT_TO_LOGIN(332),
    FILE_ACTION_PENDING_INFO(350),

    SERVICE_NOT_AVAILABLE(421),
    CANT_OPEN_DATA_CONNECTION(425),
    TRANSFER_ABORTED(426),
    FILE_BUSY(450),
    ERROR_PROCESSING_ABORTED(451),
    NOT_ENOUGH_STORAGE(452),

    SYNTAX_ERROR(500),
    BAD_PARAMETERS(501),
    NOT_IMPLEMENTED(502),
    BAD_SEQUENCE_OF_COMMANDS(503),
    COMMAND_NOT_IMPLEMENTED_FOR_PARAMETER(504),
    NOT_LOGGED_IN(530),
    NEED_ACCOUNT_TO_STORE_FILES(532),
    REQUESTED_ACTION_NOT_TAKEN(550),
    PAGE_TYPE_UNKNOWN(551),
    EXCEEDED_STORAGE_ALLOCATION(552),
    FILENAME_NOT_ALLOWED(553);

    public final int code;

    ResponseTypes(int code) {
        this.code = code;
    }
}
